TOKENS = [
    {"q": "0x" + "aa" * 20, "k": "addr"},
    {"q": "0x" + "AA" * 20, "k": "addr"},
    {"q": "0x" + "bb" * 20 + "bbbbbbbbbbbbbbbbbbbbbbbb", "k": "tx"},
    {"q": "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc", "k": "tx"},
    {"q": "0x3c7e...cd34", "k": "shorthex"},
    {"q": "0x3c7e…cd34", "k": "shorthex"},
    {"q": "3c7e34...cd56", "k": "shorthex"},
    {"q": "abc...def", "k": "text"},
    {"q": "Zq7Kp2…Mx3N", "k": "shortb58"},
    {"q": "Zq7Kp2...Mx3N", "k": "shortb58"},
    {"q": "AbCd…EfGh", "k": "shortb58"},
    {"q": "Zq7Kp2" * 7 + "Mx", "k": "b58x"},
    {"q": "Zq7Kp2" * 14 + "Mx3N", "k": "b58x"},
    {"q": "0x12", "k": "hexp"},
    {"q": "0x3c7e", "k": "hexp"},
    {"q": "3c7e34", "k": "hexp"},
    {"q": "ABCD1234", "k": "hexp"},
    {"q": "deadbeef", "k": "text"},
    {"q": "abcdef", "k": "text"},
    {"q": "ABCDEF", "k": "ticker"},
    {"q": "2026-10-02", "k": "date"},
    {"q": "2026-09", "k": "date"},
    {"q": "10/2", "k": "date"},
    {"q": "어제", "k": "date"},
    {"q": "오늘", "k": "date"},
    {"q": "2026", "k": "date"},
    {"q": "2026-13", "k": "baddate"},
    {"q": "9999-12", "k": "baddate"},
    {"q": "2026-02-30", "k": "baddate"},
    {"q": "005930", "k": "numtext"},
    {"q": "12345", "k": "numtext"},
    {"q": "0999", "k": "text"},
    {"q": "999", "k": "text"},
    {"q": "1,000", "k": "amount"},
    {"q": "$1,500", "k": "amount"},
    {"q": "1000.5", "k": "amount"},
    {"q": "ETH", "k": "ticker"},
    {"q": "$ETH", "k": "ticker"},
    {"q": "1INCH", "k": "ticker"},
    {"q": "ETH2", "k": "ticker"},
    {"q": "ZQ7KP2MX", "k": "ticker"},
    {"q": "Hb3C", "k": "b58p"},
    {"q": "Rt5w", "k": "b58p"},
    {"q": "AbCd", "k": "b58p"},
    {"q": "aBcD", "k": "b58p"},
    {"q": "Zq7Kp2", "k": "b58p"},
    {"q": "zq7kp2mx", "k": "b58p"},
    {"q": "ZQ7KP2MXAB3", "k": "b58p"},
    {"q": "Web3", "k": "b58p"},
    {"q": "Pepe", "k": "text"},
    {"q": "Solana", "k": "text"},
    {"q": "Ethereum", "k": "text"},
    {"q": "1inch", "k": "text"},
    {"q": "eth2", "k": "text"},
    {"q": "abc1", "k": "text"},
    {"q": "sol", "k": "text"},
    {"q": "pepe", "k": "text"},
    {"q": "비트", "k": "alias"},
    {"q": "ㅂㅌ", "k": "alias"},
    {"q": "브릿지", "k": "text"},
    {"q": "스왑", "k": "text"},
]

MULTI = [
    {"q": "ETH 브릿지", "ticks": ["ETH"], "b58p": []},
    {"q": "ETH BTC", "ticks": ["ETH", "BTC"], "b58p": []},
    {"q": "브릿지 ETH 자금", "ticks": ["ETH"], "b58p": []},
    {"q": "AbCd 전송", "ticks": [], "b58p": ["AbCd"]},
    {"q": "$SOL Zq7Kp2 보상", "ticks": ["SOL"], "b58p": ["Zq7Kp2"]},
    {"q": "Pepe 매수", "ticks": [], "b58p": []},
]

CONDS = [
    {"q": "-chain:베이스 coin:eth", "srv": ["coin:ETH", "-chain:base"]},
    {"q": "coin:ETH -chain:base", "srv": ["coin:ETH", "-chain:base"]},
    {"q": "chain:이더리움", "srv": ["chain:eth"]},
    {"q": "chain:ethereum", "srv": ["chain:eth"]},
    {"q": "chain:mainnet", "srv": ["chain:eth"]},
    {"q": "chain:erc20", "srv": ["chain:eth"]},
    {"q": "chain:Base", "srv": ["chain:base"]},
    {"q": "-chain:BASE", "srv": ["-chain:base"]},
    {"q": "chain:arb", "srv": ["chain:arbitrum"]},
    {"q": "chain:아비트럼", "srv": ["chain:arbitrum"]},
    {"q": "chain:op", "srv": ["chain:optimism"]},
    {"q": "chain:옵티미즘", "srv": ["chain:optimism"]},
    {"q": "chain:matic", "srv": ["chain:polygon"]},
    {"q": "chain:pol", "srv": ["chain:polygon"]},
    {"q": "chain:폴리곤", "srv": ["chain:polygon"]},
    {"q": "chain:bnb", "srv": ["chain:bsc"]},
    {"q": "chain:bep20", "srv": ["chain:bsc"]},
    {"q": "chain:BSC", "srv": ["chain:bsc"]},
    {"q": "chain:solana", "srv": ["chain:sol"]},
    {"q": "chain:솔라나", "srv": ["chain:sol"]},
    {"q": "-chain:Solana", "srv": ["-chain:sol"]},
    {"q": "chain:xdai", "srv": ["chain:gnosis"]},
    {"q": "chain:avax", "srv": ["chain:avalanche"]},
    {"q": "chain:아발란체", "srv": ["chain:avalanche"]},
    {"q": "chain:trc20", "srv": ["chain:tron"]},
    {"q": "chain:trx", "srv": ["chain:tron"]},
    {"q": "chain:트론", "srv": ["chain:tron"]},
    {"q": "chain:bera", "srv": ["chain:berachain"]},
    {"q": "chain:0G", "srv": ["chain:zerog"]},
    {"q": "chain:Swellchain", "srv": ["chain:swell"]},
    {"q": "chain:zkSync", "srv": ["chain:zksync"]},
    {"q": "chain:HyperEVM", "srv": ["chain:hyperevm"]},
    {"q": "chain:MegaETH", "srv": ["chain:megaeth"]},
    {"q": "chain:opBNB", "srv": ["chain:opbnb"]},
    {"q": "chain:ApeChain", "srv": ["chain:apechain"]},
    {"q": "chain:Robinhood", "srv": ["chain:robinhood"]},
    {"q": "type:withdraw", "srv": ["type:withdraw"]},
    {"q": "-type:withdraw", "srv": ["-type:withdraw"]},
    {"q": "-type:출금", "srv": ["-type:withdraw"]},
    {"q": "type:보냄", "srv": ["type:withdraw"]},
    {"q": "type:send", "srv": ["type:transfer"]},
    {"q": "type:전송", "srv": ["type:transfer"]},
    {"q": "type:이동", "srv": ["type:transfer"]},
    {"q": "type:fee", "srv": ["type:gas"]},
    {"q": "type:가스", "srv": ["type:gas"]},
    {"q": "-type:수수료", "srv": ["-type:gas"]},
    {"q": "-type:gas", "srv": ["-type:gas"]},
    {"q": "type:받음", "srv": ["type:deposit"]},
    {"q": "type:입금", "srv": ["type:deposit"]},
    {"q": "type:유동성", "srv": ["type:lp"]},
    {"q": "type:스왑", "srv": ["type:swap"]},
    {"q": "type:매도", "srv": ["type:sell"]},
    {"q": "kind:buy", "srv": ["type:buy"]},
    {"q": "-type:airdrop", "srv": []},
    {"q": "ex:업비트", "srv": ["ex:upbit"]},
    {"q": "-ex:바이낸스", "srv": ["-ex:binance"]},
    {"q": "ex:gate.io", "srv": ["ex:gate"]},
    {"q": "-ex:Bybit", "srv": ["-ex:bybit"]},
    {"q": "has:메모", "srv": ["has:memo"]},
    {"q": "-has:memo", "srv": ["-has:memo"]},
    {"q": "-coin:eth", "srv": ["-coin:ETH"]},
    {"q": "sym:btc", "srv": ["coin:BTC"]},
    {"q": "after:2026-09", "srv": ["after:2026-09-01"]},
    {"q": "before:2026-09", "srv": ["before:2026-09-30"]},
    {"q": "on:2026-10-02", "srv": ["after:2026-10-02", "before:2026-10-02"]},
    {"q": "after:2026-02 before:2026-02", "srv": ["after:2026-02-01", "before:2026-02-28"]},
    {"q": "wallet:콜드", "srv": ["wallet:콜드"]},
    {"q": "-wallet:핫 -wallet:콜드", "srv": ["-wallet:핫", "-wallet:콜드"]},
    {"q": "addr:" + "0x" + "AB" * 20, "srv": ["addr:" + "0x" + "ab" * 20]},
    {"q": "tx:0x3C7E", "srv": ["tx:0x3c7e"]},
    {"q": "pnl:<0", "srv": ["pnl:<0"]},
    {"q": "amt:>1000", "srv": ["amt:>1000"]},
    {"q": "coin:ETH -chain:base -type:withdraw -ex:upbit -has:memo -wallet:핫", "srv": ["coin:ETH", "-chain:base", "-type:withdraw", "-ex:upbit", "-has:memo", "-wallet:핫"]},
]

EVTYPES = [
    {"k": "온체인 매도", "d": "Base · 스왑 매도", "t": ["swap", "sell"]},
    {"k": "온체인 매수", "d": "BSC · 스왑", "t": ["swap", "buy"]},
    {"k": "온체인 매수", "d": "Base · 토큰 받음", "t": ["buy"]},
    {"k": "거래소 매도", "d": "업비트 · 체결", "t": ["sell"]},
    {"k": "거래소 매수", "d": "바이낸스 · 현물 체결", "t": ["buy"]},
    {"k": "LP 전환 매도", "d": "풀 안에서 스테이블로 전환", "t": ["lp"]},
    {"k": "유동성 추가", "d": "Base", "t": ["lp"]},
    {"k": "입금", "d": "업비트 입금", "t": ["deposit"]},
    {"k": "외부 전송", "d": "Base → 외부 0x12…", "t": ["withdraw"]},
    {"k": "전송", "d": "Robinhood → 외부 0x92…", "t": ["withdraw"]},
    {"k": "전송", "d": "Base · 보낸 내역", "t": ["withdraw"]},
    {"k": "전송", "d": "Solana · 스테이킹 보상", "t": ["transfer"]},
    {"k": "가스", "d": "Ethereum · 가스", "t": ["gas"]},
    {"k": "실패 tx", "d": "가스 소모 · Base", "t": ["gas"]},
    {"k": "출금", "d": "업비트 출금", "t": ["transfer"]},
    {"k": "대사 정정", "d": "바이낸스", "t": ["transfer"]},
]

EVCHAINS = [
    {"d": "Base · 스왑 매도", "src": "w:" + "0x" + "cd" * 20, "card": "", "cks": ["base"]},
    {"d": "Robinhood → 외부 0x92…", "src": "w:" + "0x" + "cd" * 20, "card": "", "cks": ["robinhood"]},
    {"d": "Abstract/Arbitrum/Base · 브릿지", "src": "w:" + "0x" + "cd" * 20, "card": "", "cks": ["abstract", "arbitrum", "base"]},
    {"d": "바이낸스 · 현물 체결", "src": "ex:binance", "card": "Base", "cks": []},
    {"d": "스왑", "src": "w:" + "0x" + "cd" * 20, "card": "Base", "cks": ["base"]},
    {"d": "스왑", "src": "w:" + "0x" + "cd" * 20, "card": "Ethereum · Base 외 6", "cks": []},
    {"d": "스왑", "src": "ex:upbit", "card": "Base", "cks": []},
    {"d": "Solana · 스테이킹 보상", "src": "w:" + "Zq7Kp2" * 6 + "Mx", "card": "", "cks": ["sol"]},
    {"d": "BNB Chain · 스왑", "src": "w:" + "0x" + "cd" * 20, "card": "", "cks": ["bsc"]},
    {"d": "Base 외 2 · 받음", "src": "w:" + "0x" + "cd" * 20, "card": "", "cks": ["base"]},
    {"d": "업비트 출금 → 외부", "src": "w:" + "0x" + "cd" * 20, "card": "", "cks": []},
    {"d": "토큰 받음", "src": "w:" + "0x" + "cd" * 20, "card": "", "cks": []},
]

SAMPLES = {"tokens": TOKENS, "multi": MULTI, "conds": CONDS, "evtypes": EVTYPES, "evchains": EVCHAINS}
